# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 243ba7790eefcdf68a419e511f44fa761037322331ea9c886f1dda3c1fe7447b3223a98589dfcc22151497212f46b9b363884ebf052385014f9130674eb8aa6e

test:
  secret_key_base: 3177cb841a153a863527c7396a6567d806cd40cf0170d72a8a120e03086011123d3678d15e9cb111b2441d0c057af206895b87ce07992b286f9946a1d5349315

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
